time="2023-11-29T11:32:24+01:00" level=warning msg="Found orphan containers ([kg-prototypes-llm-run-902c17fc8100 kg-prototypes-llm-run-a9f3f4bffbdd kg-prototypes-llm-run-907971f48afc kg-prototypes-llm-run-8768ee5f2d34 kg-prototypes-llm-run-0017fc3c25dc kg-prototypes-llm-run-1fa94606923a llm kg-prototypes-postgres-1 kg-prototypes-neo4j-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
 Container pgdatabase  Running
 Container pdfparser  Running
 Container redis  Running
 Container arangodb  Running
 Container graphdatabase  Running
 Container elasticsearch  Running
 Container appserver  Recreate
 Container appserver  Recreated
Attaching to appserver
appserver  |  * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
appserver  | Traceback (most recent call last):
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
appserver  |     return fn()
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
appserver  |     return _ConnectionFairy._checkout(self)
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
appserver  |     fairy = _ConnectionRecord.checkout(pool)
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
appserver  |     rec = pool._do_get()
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
appserver  |     return self._create_connection()
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
appserver  |     return _ConnectionRecord(self)
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
appserver  |     self.__connect(first_connect_check=True)
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
appserver  |     pool.logger.debug("Error on connect(): %s", e)
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
appserver  |     compat.raise_(
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
appserver  |     raise exception
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
appserver  |     connection = pool._invoke_creator(self)
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
appserver  |     return dialect.connect(*cargs, **cparams)
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 508, in connect
appserver  |     return self.dbapi.connect(*cargs, **cparams)
appserver  |   File "/usr/local/lib64/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
appserver  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
appserver  | psycopg2.OperationalError: could not translate host name "pgdatabase" to address: Name or service not known
appserver  | 
appserver  | 
appserver  | The above exception was the direct cause of the following exception:
appserver  | 
appserver  | Traceback (most recent call last):
appserver  |   File "/usr/local/bin/flask", line 8, in <module>
appserver  | 
appserver  |     sys.exit(main())
appserver  |   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 967, in main
appserver  |     cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
appserver  |   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 586, in main
appserver  |     return super(FlaskGroup, self).main(*args, **kwargs)
appserver  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
appserver  |     rv = self.invoke(ctx)
appserver  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
appserver  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
appserver  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
appserver  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
appserver  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
appserver  |     return ctx.invoke(self.callback, **ctx.params)
appserver  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
appserver  |     return __callback(*args, **kwargs)
appserver  |   File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
appserver  |     return f(get_current_context(), *args, **kwargs)
appserver  |   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 426, in decorator
appserver  |     return __ctx.invoke(f, *args, **kwargs)
appserver  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
appserver  |     return __callback(*args, **kwargs)
appserver  |   File "/usr/local/lib/python3.9/site-packages/flask_migrate/cli.py", line 136, in upgrade
appserver  |     _upgrade(directory, revision, sql, tag, x_arg)
appserver  |   File "/usr/local/lib/python3.9/site-packages/flask_migrate/__init__.py", line 96, in wrapped
appserver  |     f(*args, **kwargs)
appserver  |   File "/usr/local/lib/python3.9/site-packages/flask_migrate/__init__.py", line 271, in upgrade
appserver  |     command.upgrade(config, revision, sql=sql, tag=tag)
appserver  |   File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line 378, in upgrade
appserver  |     script.run_env()
appserver  |   File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 569, in run_env
appserver  |     util.load_python_file(self.dir, "env.py")
appserver  |   File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
appserver  |     module = load_module_py(module_id, path)
appserver  |   File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
appserver  |     spec.loader.exec_module(module)  # type: ignore
appserver  |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
appserver  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
appserver  |   File "migrations/env.py", line 301, in <module>
appserver  |     run_migrations_online()
appserver  |   File "migrations/env.py", line 281, in run_migrations_online
appserver  |     with connectable.connect() as connection:
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2263, in connect
appserver  |     return self._connection_cls(self, **kwargs)
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 104, in __init__
appserver  |     else engine.raw_connection()
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2369, in raw_connection
appserver  |     return self._wrap_pool_connect(
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
appserver  |     Connection._handle_dbapi_exception_noconnection(
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1583, in _handle_dbapi_exception_noconnection
appserver  |     util.raise_(
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
appserver  |     raise exception
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
appserver  |     return fn()
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
appserver  |     return _ConnectionFairy._checkout(self)
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
appserver  |     fairy = _ConnectionRecord.checkout(pool)
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
appserver  |     rec = pool._do_get()
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
appserver  |     return self._create_connection()
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
appserver  |     return _ConnectionRecord(self)
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
appserver  |     self.__connect(first_connect_check=True)
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
appserver  |     pool.logger.debug("Error on connect(): %s", e)
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
appserver  |     compat.raise_(
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
appserver  |     raise exception
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
appserver  |     connection = pool._invoke_creator(self)
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
appserver  |     return dialect.connect(*cargs, **cparams)
appserver  |   File "/home/n4j/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 508, in connect
appserver  |     return self.dbapi.connect(*cargs, **cparams)
appserver  |   File "/usr/local/lib64/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
appserver  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
appserver  | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "pgdatabase" to address: Name or service not known
appserver  | 
appserver  | (Background on this error at: http://sqlalche.me/e/13/e3q8)
appserver  | 
Aborting on container exit...
appserver exited with code 1
 Container appserver  Stopping
 Container appserver  Stopped
